import TopNavBar from '@/components/navbar/TopNavBar'

import './globals.scss'
import './globals.css'

import { Inter } from 'next/font/google'
import SideNavBar from '@/components/navbar/SideNavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + ' text-white z-[1]'}>
        <SideNavBar />
        <TopNavBar />
        <div className="flex-1 text-black z-[2]">{children}</div>
      </body>
    </html>
  )
}
